(define finite (cons-stream 1 (cons-stream 2 (cons-stream 3 nil))))
(define (partial-sums stream)
  (define (func sum stream)
    (if (null? stream)
      nil
      (cons-stream (+ sum (car stream)) (func (+ sum (car stream)) (cdr-stream stream)))
    )
  )
  (func 0 stream)
)
(define finite-sums (partial-sums finite))
(car finite-sums)
(car (cdr-stream finite-sums))
(car (cdr-stream (cdr-stream finite-sums)))
(cdr-stream (cdr-stream (cdr-stream finite-sums)))